_meta_: {}
bundle_root: /HN_pre_3.14/segresnet_0
ckpt_path: $@bundle_root + '/model'
mlflow_tracking_uri: $@ckpt_path + '/mlruns/'
mlflow_experiment_name: Auto3DSeg
data_file_base_dir: /input/images/pre-rt-t2w-head-neck/
data_list_file_path: /tmp/HN_preRT_data.json
modality: mri
fold: 0
input_channels: 1
output_classes: 3
class_names: [tumor, node]
class_index: null
debug: false
ckpt_save: true
cache_rate: null
roi_size: [256, 256, 120]
auto_scale_allowed: true
auto_scale_batch: true
auto_scale_roi: false
auto_scale_filters: false
quick: false
channels_last: true
validate_final_original_res: true
calc_val_loss: false
amp: true
log_output_file: null
cache_class_indices: null
early_stopping_fraction: 0.001
determ: false
orientation_ras: true
crop_foreground: true
learning_rate: 0.0002
batch_size: 1
num_images_per_batch: 1
num_epochs: 556
num_warmup_epochs: 3
sigmoid: false
resample: false
resample_resolution: [0.5, 0.5, 1.1999970677854643]
crop_mode: ratio
normalize_mode: meanstd
intensity_bounds: [110.79653445879619, 613.4528028700087]
num_epochs_per_validation: null
num_epochs_per_saving: 1
num_workers: 4
num_steps_per_image: null
num_crops_per_image: 1
loss: {_target_: DiceCELoss, include_background: true, squared_pred: true, smooth_nr: 0,
  smooth_dr: 1.0e-05, softmax: $not @sigmoid, sigmoid: $@sigmoid, to_onehot_y: $not
    @sigmoid}
optimizer: {_target_: torch.optim.AdamW, lr: '@learning_rate', weight_decay: 1.0e-05}
network:
  _target_: SegResNetDS
  init_filters: 32
  blocks_down: [1, 2, 2, 4, 4]
  norm: INSTANCE_NVFUSER
  in_channels: '@input_channels'
  out_channels: '@output_classes'
  dsdepth: 4
finetune: {enabled: true, ckpt_name: /home/dlabella29/Auto3DSegDL/Auto3DSegDL/HN_all_3_9.11.24_pre/segresnet_0/model/model.pt}
validate: {enabled: false, ckpt_name: $@bundle_root + '/model/model.pt', output_path: $@bundle_root
    + '/prediction_validation', save_mask: false, invert: true}
infer: {enabled: false, ckpt_name: $@bundle_root + '/model/model.pt', output_path: $@bundle_root
    + '/prediction_' + @infer#data_list_key, data_list_key: testing}
anisotropic_scales: true
spacing_median: [0.5, 0.5, 2.0]
spacing_lower: [0.4000000059604645, 0.4000000059604645, 1.0]
spacing_upper: [0.9848484995722021, 0.9848484992980957, 2.1425000001983037]
image_size_mm_median: [256.0, 256.0, 148.0]
image_size_mm_90: [520.0000077741228, 520.0000076293945, 164.81987950440205]
image_size: [1040, 1040, 137]
